const differentAvailabilityData = {
    "Amanda": {
        Monday: { startTime: "8:00 AM", endTime: "4:00 PM" }
    }
};

const ptoData = {
    "Amanda": {
        Wednesday: true // John is on PTO on Wednesday
    },
};


const peopleData = {
    "Amanda": {
        team: "Green",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Amanda"],
        pto: ptoData["Amanda"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Amber": {
        team: "Green",
        availability: {
            Monday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Tuesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Wednesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Thursday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Friday: { startTime: "08:00 AM", endTime: "04:30 PM" },
        },
        differentAvailability: differentAvailabilityData["Amber"],
        pto: ptoData["Amber"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1.0,
    },
    "Anja": {
        team: "Green",
        availability: {
            Monday: { startTime: "08:00 AM", endTime: "03:30 PM" },
            Wednesday: { startTime: "08:00 AM", endTime: "03:30 PM" },
            Thursday: { startTime: "08:00 AM", endTime: "12:00 PM" },
            Friday: { startTime: "08:00 AM", endTime: "03:30 PM" },
        },
        differentAvailability: differentAvailabilityData["Anja"],
        pto: ptoData["Anja"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: .75,
    },
    "Ashley": {
        team: "Green",
        availability: {
            Monday: { startTime: "07:00 AM", endTime: "03:30 PM" },
            Tuesday: { startTime: "07:00 AM", endTime: "03:30 PM" },
            Wednesday: { startTime: "07:00 AM", endTime: "03:30 PM" },
            Thursday: { startTime: "07:00 AM", endTime: "03:30 PM" },
            Friday: { startTime: "07:00 AM", endTime: "03:30 PM" },
        },
        differentAvailability: differentAvailabilityData["Ashley"],
        pto: ptoData["Ashley"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Barbara": {
        team: "Green",
        availability: {
            Monday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Tuesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Wednesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Thursday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Friday: { startTime: "08:00 AM", endTime: "04:30 PM" },
        },
        differentAvailability: differentAvailabilityData["Barbara"],
        pto: ptoData["Barbara"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1.0,
    },
    "Bree": {
        team: "Green",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Bree"],
        pto: ptoData["Bree"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Carrie": {
        team: "Green",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Carrie"],
        pto: ptoData["Carrie"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Cheri": {
        team: "Blue",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Cheri"],
        pto: ptoData["Cheri"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Danielle": {
        team: "Blue",
        availability: {
            Monday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Tuesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Wednesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Thursday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Friday: { startTime: "08:00 AM", endTime: "04:30 PM" },
        },
        differentAvailability: differentAvailabilityData["Danielle"],
        pto: ptoData["Danielle"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Diane": {
        team: "Green",
        availability: {
            Monday: { startTime: "07:00 AM", endTime: "03:30 PM" },
            Tuesday: { startTime: "07:00 AM", endTime: "03:30 PM" },
            Wednesday: { startTime: "07:00 AM", endTime: "03:30 PM" },
            Thursday: { startTime: "07:00 AM", endTime: "03:30 PM" },
            Friday: { startTime: "07:00 AM", endTime: "03:30 PM" },
        },
        differentAvailability: differentAvailabilityData["Diane"],
        pto: ptoData["Diane"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Emily": {
        team: "Blue",
        availability: {
            Monday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Tuesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Wednesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Thursday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Friday: { startTime: "08:00 AM", endTime: "04:30 PM" },
        },
        differentAvailability: differentAvailabilityData["Emily"],
        pto: ptoData["Emily"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Jamie": {
        team: "Blue",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Jamie"],
        pto: ptoData["Jamie"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Jennifer": {
        team: "Blue",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Jennifer"],
        pto: ptoData["Jennifer"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Jen": {
        team: "Blue",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Jen"],
        pto: ptoData["Jen"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Julie": {
        team: "Blue",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Julie"],
        pto: ptoData["Julie"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Justine": {
        team: "Blue",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Justine"],
        pto: ptoData["Justine"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Katelynn": {
        team: "Green",
        availability: {
            Monday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Tuesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Wednesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Thursday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Friday: { startTime: "08:00 AM", endTime: "04:30 PM" },
        },
        differentAvailability: differentAvailabilityData["Katelynn"],
        pto: ptoData["Katelynn"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1.0,
    },
    "Lee": {
        team: "Green",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Lee"],
        pto: ptoData["Lee"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Lisa": {
        team: "Blue",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Lisa"],
        pto: ptoData["Lisa"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Megan P": {
        team: "Green",
        availability: {
            Monday: { startTime: "08:00 AM", endTime: "03:30 PM" },
            Tuesday: { startTime: "08:00 AM", endTime: "03:30 PM" },
            Wednesday: { startTime: "08:00 AM", endTime: "02:30 PM" },
        },
        differentAvailability: differentAvailabilityData["Megan P"],
        pto: ptoData["Megan P"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1.0,
    },
    "Megan S": {
        team: "Blue",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Megan S"],
        pto: ptoData["Megan S"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Melissa K": {
        team: "Green",
        availability: {
            Monday: { startTime: "06:30 AM", endTime: "03:00 PM" },
            Tuesday: { startTime: "06:30 AM", endTime: "0:00 PM" },
            Wednesday: { startTime: "06:30 AM", endTime: "03:00 PM" },
            Thursday: { startTime: "06:30 AM", endTime: "03:00 PM" },
            Friday: { startTime: "06:30 AM", endTime: "03:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Melissa K"],
        pto: ptoData["Melissa K"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Melissa O": {
        team: "Blue",
        availability: {
            Monday: { startTime: "06:00 AM", endTime: "02:30 PM" },
            Tuesday: { startTime: "06:00 AM", endTime: "02:30 PM" },
            Wednesday: { startTime: "06:00 AM", endTime: "02:30 PM" },
            Thursday: { startTime: "06:00 AM", endTime: "02:30 PM" },
            Friday: { startTime: "06:00 AM", endTime: "02:30 PM" },
        },
        differentAvailability: differentAvailabilityData["Melissa O"],
        pto: ptoData["Melissa O"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Michelle": {
        team: "Green",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Michelle"],
        pto: ptoData["Michelle"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Nicole": {
        team: "Green",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Nicole"],
        pto: ptoData["Nicole"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Ong": {
        team: "Green",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Ong"],
        pto: ptoData["Ong"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Robin": {
        team: "Green",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Robin"],
        pto: ptoData["Robin"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Roxie": {
        team: "Green",
        availability: {
            Monday: { startTime: "07:00 AM", endTime: "03:30 PM" },
            Tuesday: { startTime: "07:00 AM", endTime: "03:30 PM" },
            Wednesday: { startTime: "07:00 AM", endTime: "03:30 PM" },
            Thursday: { startTime: "07:00 AM", endTime: "03:30 PM" },
            Friday: { startTime: "07:00 AM", endTime: "03:30 PM" },
        },
        differentAvailability: differentAvailabilityData["Roxie"],
        pto: ptoData["Roxie"],
        trainingStatus: {
            'Plastics / Plastic': "Trained",
            'General': "Trained",
            'Neuro/Spine': "Trained",
            'Orthopedics': "Trained",
            'ENT/Dental/Anesthesia': "Trained",
            'Opthalmalogy': "Trained",
            'WC Patient': "Trained",
            'Endo WQ': "Not Trained",
            'GI': "Not Trained",
            'Gynecology': "Not Trained",
            'Urology': "Not Trained",
            'Podiatry': "Not Trained",
            'Procedural': "Not Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Sarah": {
        team: "Blue",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Sarah"],
        pto: ptoData["Sarah"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Sepedty": {
        team: "Blue",
        availability: {
            Monday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Tuesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Wednesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Thursday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Friday: { startTime: "08:00 AM", endTime: "04:30 PM" },
        },
        differentAvailability: differentAvailabilityData["Sepedty"],
        pto: ptoData["Sepedty"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Shannon": {
        team: "Blue",
        availability: {
            Monday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Tuesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Wednesday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Thursday: { startTime: "07:30 AM", endTime: "04:00 PM" },
            Friday: { startTime: "07:30 AM", endTime: "04:00 PM" },
        },
        differentAvailability: differentAvailabilityData["Shannon"],
        pto: ptoData["Shannon"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
    "Victoria": {
        team: "Blue",
        availability: {
            Monday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Tuesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Wednesday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Thursday: { startTime: "08:00 AM", endTime: "04:30 PM" },
            Friday: { startTime: "08:00 AM", endTime: "04:30 PM" },
        },
        differentAvailability: differentAvailabilityData["Victoria"],
        pto: ptoData["Victoria"],
        trainingStatus: {
            'Plastics / Plastic': "Not Trained",
            'General': "Not Trained",
            'Neuro/Spine': "Not Trained",
            'Orthopedics': "Not Trained",
            'ENT/Dental/Anesthesia': "Not Trained",
            'Opthalmalogy': "Not Trained",
            'WC Patient': "Not Trained",
            'Endo WQ': "Trained",
            'GI': "Trained",
            'Gynecology': "Trained",
            'Urology': "Trained",
            'Podiatry': "Trained",
            'Procedural': "Trained",
            'Faxes / IB Pool': "Trained",
            'Emails/Voicemail': "Trained",
        },
        FTE: 1,
    },
};

export { peopleData };